/*
 * generated by Xtext 2.25.0
 */
package org.xtext.mdd.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDgenScopeProvider extends DelegatingScopeProvider {
}
