/*
 * generated by Xtext 2.25.0
 */
package org.xtext.mdd;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class DgenStandaloneSetup extends DgenStandaloneSetupGenerated {

	public static void doSetup() {
		new DgenStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
