package org.xtext.mdd.generator;

import com.google.common.base.Objects;
import com.google.common.collect.Iterables;
import com.google.inject.Inject;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.eclipse.xtext.naming.QualifiedName;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;
import org.xtext.mdd.dgen.Entity;
import org.xtext.mdd.dgen.ViewOptions;

@SuppressWarnings("all")
public class DjangoTemplateGenerator extends AbstractGenerator {
  @Inject
  @Extension
  private IQualifiedNameProvider _iQualifiedNameProvider;
  
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    fsa.generateFile("app/templates/bootstrap/index.html", this.createIndex(resource));
  }
  
  private CharSequence createIndex(final Resource resource) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("\t");
    _builder.append("<!DOCTYPE html>");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("{% load static %}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<html lang=\"en\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<head>");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("<meta charset=\"utf-8\">");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("<meta name=\"description\" content=\"\">");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("<meta name=\"author\" content=\"\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("<title>DGen</title>");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("<!-- Custom fonts for this template-->");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("<link rel=\"stylesheet\" href=\"https://pro.fontawesome.com/releases/v5.10.0/css/all.css\" integrity=\"sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p\" crossorigin=\"anonymous\"/>");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("<link href=\"https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i\" rel=\"stylesheet\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("<!-- Custom styles for this template-->");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("<link href=\"{% static \'css/styles.css\' %}\" rel=\"stylesheet\">");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("<link href=\"{% static \'css/sb-admin-2.min.css\' %}\" rel=\"stylesheet\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</head>");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<body id=\"page-top\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("<!-- Page Wrapper -->");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("<div id=\"wrapper\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("<!-- Sidebar -->");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("<ul class=\"navbar-nav sidebar sidebar-dark\" id=\"dgen-sb\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t      ");
    _builder.append("<!-- Sidebar - Brand -->");
    _builder.newLine();
    _builder.append("\t      ");
    _builder.append("<a class=\"sidebar-brand d-flex align-items-center justify-content-center\" id=\"dgen-sb-brand\">");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("<div class=\"sidebar-brand-icon\">");
    _builder.newLine();
    _builder.append("\t          ");
    _builder.append("<i class=\"fas fa-project-diagram\"></i>");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("<div class=\"sidebar-brand-text mx-3\">Dgen</div>");
    _builder.newLine();
    _builder.append("\t      ");
    _builder.append("</a>");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t      ");
    _builder.append("<!-- Divider -->");
    _builder.newLine();
    _builder.append("\t      ");
    _builder.append("<hr class=\"sidebar-divider my-0\">");
    _builder.newLine();
    _builder.newLine();
    {
      Iterable<Entity> _filter = Iterables.<Entity>filter(IteratorExtensions.<EObject>toIterable(resource.getAllContents()), Entity.class);
      for(final Entity e : _filter) {
        _builder.append("\t\t\t");
        String _xtrycatchfinallyexpression = null;
        try {
          String _xblockexpression = null;
          {
            final String group = e.getViews().getViewGroup().getName();
            int _length = group.length();
            boolean _greaterThan = (_length > 0);
            if (_greaterThan) {
            }
            _xblockexpression = "group";
          }
          _xtrycatchfinallyexpression = _xblockexpression;
        } catch (final Throwable _t) {
          if (_t instanceof Exception) {
            _xtrycatchfinallyexpression = "option";
          } else {
            throw Exceptions.sneakyThrow(_t);
          }
        }
        final String what = _xtrycatchfinallyexpression;
        _builder.newLineIfNotEmpty();
        {
          boolean _equals = Objects.equal(what, "group");
          if (_equals) {
            {
              String _name = e.getViews().getViewGroup().getName();
              boolean _equals_1 = Objects.equal(_name, "All");
              if (_equals_1) {
                _builder.append("\t\t\t");
                _builder.append("<!-- ");
                QualifiedName _fullyQualifiedName = this._iQualifiedNameProvider.getFullyQualifiedName(e);
                _builder.append(_fullyQualifiedName, "\t\t\t");
                _builder.append(" -->");
                _builder.newLineIfNotEmpty();
                _builder.append("\t\t\t");
                _builder.append("<li class=\"nav-item\">");
                _builder.newLine();
                _builder.append("\t\t\t");
                _builder.append("\t");
                _builder.append("<a class=\"nav-link\" href=\"{% url \'");
                String _lowerCase = e.getName().toLowerCase();
                _builder.append(_lowerCase, "\t\t\t\t");
                _builder.append("_read\' %}\">");
                _builder.newLineIfNotEmpty();
                _builder.append("\t\t\t");
                _builder.append("\t\t");
                _builder.append("<i class=\"fad fa-sitemap\"></i>");
                _builder.newLine();
                _builder.append("\t\t\t");
                _builder.append("\t\t");
                _builder.append("<span>");
                QualifiedName _fullyQualifiedName_1 = this._iQualifiedNameProvider.getFullyQualifiedName(e);
                _builder.append(_fullyQualifiedName_1, "\t\t\t\t\t");
                _builder.append("</span>");
                _builder.newLineIfNotEmpty();
                _builder.append("\t\t\t");
                _builder.append("\t");
                _builder.append("</a>");
                _builder.newLine();
                _builder.append("\t\t\t");
                _builder.append("</li>");
                _builder.newLine();
              }
            }
          } else {
            {
              final Function1<ViewOptions, Boolean> _function = (ViewOptions opt) -> {
                return Boolean.valueOf(opt.getName().equals("Read"));
              };
              int _size = IterableExtensions.size(IterableExtensions.<ViewOptions>filter(e.getViews().getViewOption(), _function));
              boolean _greaterThan = (_size > 0);
              if (_greaterThan) {
                _builder.append("\t\t\t");
                _builder.append("<!-- ");
                QualifiedName _fullyQualifiedName_2 = this._iQualifiedNameProvider.getFullyQualifiedName(e);
                _builder.append(_fullyQualifiedName_2, "\t\t\t");
                _builder.append(" -->");
                _builder.newLineIfNotEmpty();
                _builder.append("\t\t\t");
                _builder.append("<li class=\"nav-item\">");
                _builder.newLine();
                _builder.append("\t\t\t");
                _builder.append("\t");
                _builder.append("<a class=\"nav-link\" href=\"{% url \'");
                String _lowerCase_1 = e.getName().toLowerCase();
                _builder.append(_lowerCase_1, "\t\t\t\t");
                _builder.append("_read\' %}\">");
                _builder.newLineIfNotEmpty();
                _builder.append("\t\t\t");
                _builder.append("\t\t");
                _builder.append("<i class=\"fad fa-sitemap\"></i>");
                _builder.newLine();
                _builder.append("\t\t\t");
                _builder.append("\t\t");
                _builder.append("<span>");
                QualifiedName _fullyQualifiedName_3 = this._iQualifiedNameProvider.getFullyQualifiedName(e);
                _builder.append(_fullyQualifiedName_3, "\t\t\t\t\t");
                _builder.append("</span>");
                _builder.newLineIfNotEmpty();
                _builder.append("\t\t\t");
                _builder.append("\t");
                _builder.append("</a>");
                _builder.newLine();
                _builder.append("\t\t\t");
                _builder.append("</li>");
                _builder.newLine();
              } else {
                final Function1<ViewOptions, Boolean> _function_1 = (ViewOptions opt) -> {
                  return Boolean.valueOf(opt.getName().equals("Create"));
                };
                int _size_1 = IterableExtensions.size(IterableExtensions.<ViewOptions>filter(e.getViews().getViewOption(), _function_1));
                boolean _greaterThan_1 = (_size_1 > 0);
                if (_greaterThan_1) {
                  _builder.append("\t\t\t");
                  _builder.append("<!-- ");
                  QualifiedName _fullyQualifiedName_4 = this._iQualifiedNameProvider.getFullyQualifiedName(e);
                  _builder.append(_fullyQualifiedName_4, "\t\t\t");
                  _builder.append(" -->");
                  _builder.newLineIfNotEmpty();
                  _builder.append("\t\t\t");
                  _builder.append("<li class=\"nav-item\">");
                  _builder.newLine();
                  _builder.append("\t\t\t");
                  _builder.append("\t");
                  _builder.append("<a class=\"nav-link\" href=\"{% url \'");
                  String _lowerCase_2 = e.getName().toLowerCase();
                  _builder.append(_lowerCase_2, "\t\t\t\t");
                  _builder.append("_add\' %}\">");
                  _builder.newLineIfNotEmpty();
                  _builder.append("\t\t\t");
                  _builder.append("\t\t");
                  _builder.append("<i class=\"fad fa-sitemap\"></i>");
                  _builder.newLine();
                  _builder.append("\t\t\t");
                  _builder.append("\t\t");
                  _builder.append("<span>");
                  QualifiedName _fullyQualifiedName_5 = this._iQualifiedNameProvider.getFullyQualifiedName(e);
                  _builder.append(_fullyQualifiedName_5, "\t\t\t\t\t");
                  _builder.append("</span>");
                  _builder.newLineIfNotEmpty();
                  _builder.append("\t\t\t");
                  _builder.append("\t");
                  _builder.append("</a>");
                  _builder.newLine();
                  _builder.append("\t\t\t");
                  _builder.append("</li>");
                  _builder.newLine();
                } else {
                  final Function1<ViewOptions, Boolean> _function_2 = (ViewOptions opt) -> {
                    return Boolean.valueOf(opt.getName().equals("Update"));
                  };
                  int _size_2 = IterableExtensions.size(IterableExtensions.<ViewOptions>filter(e.getViews().getViewOption(), _function_2));
                  boolean _greaterThan_2 = (_size_2 > 0);
                  if (_greaterThan_2) {
                    _builder.append("\t\t\t");
                    _builder.append("<!-- ");
                    QualifiedName _fullyQualifiedName_6 = this._iQualifiedNameProvider.getFullyQualifiedName(e);
                    _builder.append(_fullyQualifiedName_6, "\t\t\t");
                    _builder.append(" -->");
                    _builder.newLineIfNotEmpty();
                    _builder.append("\t\t\t");
                    _builder.append("<li class=\"nav-item\">");
                    _builder.newLine();
                    _builder.append("\t\t\t");
                    _builder.append("\t");
                    _builder.append("<a class=\"nav-link\" href=\"{% url \'");
                    String _lowerCase_3 = e.getName().toLowerCase();
                    _builder.append(_lowerCase_3, "\t\t\t\t");
                    _builder.append("_update\' %}\">");
                    _builder.newLineIfNotEmpty();
                    _builder.append("\t\t\t");
                    _builder.append("\t\t");
                    _builder.append("<i class=\"fad fa-sitemap\"></i>");
                    _builder.newLine();
                    _builder.append("\t\t\t");
                    _builder.append("\t\t");
                    _builder.append("<span>");
                    QualifiedName _fullyQualifiedName_7 = this._iQualifiedNameProvider.getFullyQualifiedName(e);
                    _builder.append(_fullyQualifiedName_7, "\t\t\t\t\t");
                    _builder.append("</span>");
                    _builder.newLineIfNotEmpty();
                    _builder.append("\t\t\t");
                    _builder.append("\t");
                    _builder.append("</a>");
                    _builder.newLine();
                    _builder.append("\t\t\t");
                    _builder.append("</li>");
                    _builder.newLine();
                  } else {
                    final Function1<ViewOptions, Boolean> _function_3 = (ViewOptions opt) -> {
                      return Boolean.valueOf(opt.getName().equals("Delete"));
                    };
                    int _size_3 = IterableExtensions.size(IterableExtensions.<ViewOptions>filter(e.getViews().getViewOption(), _function_3));
                    boolean _greaterThan_3 = (_size_3 > 0);
                    if (_greaterThan_3) {
                      _builder.append("\t\t\t");
                      _builder.append("<!-- ");
                      QualifiedName _fullyQualifiedName_8 = this._iQualifiedNameProvider.getFullyQualifiedName(e);
                      _builder.append(_fullyQualifiedName_8, "\t\t\t");
                      _builder.append(" -->");
                      _builder.newLineIfNotEmpty();
                      _builder.append("\t\t\t");
                      _builder.append("<li class=\"nav-item\">");
                      _builder.newLine();
                      _builder.append("\t\t\t");
                      _builder.append("\t");
                      _builder.append("<a class=\"nav-link\" href=\"{% url \'");
                      String _lowerCase_4 = e.getName().toLowerCase();
                      _builder.append(_lowerCase_4, "\t\t\t\t");
                      _builder.append("_delete\' %}\">");
                      _builder.newLineIfNotEmpty();
                      _builder.append("\t\t\t");
                      _builder.append("\t\t");
                      _builder.append("<i class=\"fad fa-sitemap\"></i>");
                      _builder.newLine();
                      _builder.append("\t\t\t");
                      _builder.append("\t\t");
                      _builder.append("<span>");
                      QualifiedName _fullyQualifiedName_9 = this._iQualifiedNameProvider.getFullyQualifiedName(e);
                      _builder.append(_fullyQualifiedName_9, "\t\t\t\t\t");
                      _builder.append("</span>");
                      _builder.newLineIfNotEmpty();
                      _builder.append("\t\t\t");
                      _builder.append("\t");
                      _builder.append("</a>");
                      _builder.newLine();
                      _builder.append("\t\t\t");
                      _builder.append("</li>");
                      _builder.newLine();
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t      ");
    _builder.append("<!-- Divider -->");
    _builder.newLine();
    _builder.append("\t      ");
    _builder.append("<hr class=\"sidebar-divider d-none d-md-block\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t      ");
    _builder.append("<!-- Sidebar Toggler (Sidebar) -->");
    _builder.newLine();
    _builder.append("\t      ");
    _builder.append("<div class=\"text-center d-none d-md-inline\">");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("<button class=\"rounded-circle border-0\" id=\"sidebarToggle\"></button>");
    _builder.newLine();
    _builder.append("\t      ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("</ul>");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("<!-- End of Sidebar -->");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("<!-- Content Wrapper -->");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("<div id=\"content-wrapper\" class=\"d-flex flex-column\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t      ");
    _builder.append("<!-- Main Content -->");
    _builder.newLine();
    _builder.append("\t      ");
    _builder.append("<div id=\"content\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("<!-- Topbar -->");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("<nav class=\"navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t          ");
    _builder.append("<!-- Sidebar Toggle (Topbar) -->");
    _builder.newLine();
    _builder.append("\t          ");
    _builder.append("<button id=\"sidebarToggleTop\" class=\"btn btn-link d-md-none rounded-circle mr-3\">");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("<i class=\"fa fa-bars\"></i>");
    _builder.newLine();
    _builder.append("\t          ");
    _builder.append("</button>");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t          ");
    _builder.append("<!-- Topbar Search -->");
    _builder.newLine();
    _builder.append("\t          ");
    _builder.append("<!-- <form class=\"d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search\">");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("<div class=\"input-group\">");
    _builder.newLine();
    _builder.append("\t              ");
    _builder.append("<input type=\"text\" class=\"form-control bg-light border-0 small\" placeholder=\"Search for...\" aria-label=\"Search\" aria-describedby=\"basic-addon2\">");
    _builder.newLine();
    _builder.append("\t              ");
    _builder.append("<div class=\"input-group-append\">");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("<button class=\"btn btn-primary\" type=\"button\">");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("<i class=\"fas fa-search fa-sm\"></i>");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("</button>");
    _builder.newLine();
    _builder.append("\t              ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t          ");
    _builder.append("</form> -->");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t          ");
    _builder.append("<!-- Topbar Navbar -->");
    _builder.newLine();
    _builder.append("\t          ");
    _builder.append("<ul class=\"navbar-nav ml-auto\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("<!-- Nav Item - Search Dropdown (Visible Only XS) -->");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("<li class=\"nav-item dropdown no-arrow d-sm-none\">");
    _builder.newLine();
    _builder.append("\t              ");
    _builder.append("<a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"searchDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("<i class=\"fas fa-search fa-fw\"></i>");
    _builder.newLine();
    _builder.append("\t              ");
    _builder.append("</a>");
    _builder.newLine();
    _builder.append("\t              ");
    _builder.append("<!-- Dropdown - Messages -->");
    _builder.newLine();
    _builder.append("\t              ");
    _builder.append("<div class=\"dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in\" aria-labelledby=\"searchDropdown\">");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("<form class=\"form-inline mr-auto w-100 navbar-search\">");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("<div class=\"input-group\">");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("<input type=\"text\" class=\"form-control bg-light border-0 small\" placeholder=\"Search for...\" aria-label=\"Search\" aria-describedby=\"basic-addon2\">");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("<div class=\"input-group-append\">");
    _builder.newLine();
    _builder.append("\t                      ");
    _builder.append("<button class=\"btn btn-primary\" type=\"button\">");
    _builder.newLine();
    _builder.append("\t                        ");
    _builder.append("<i class=\"fas fa-search fa-sm\"></i>");
    _builder.newLine();
    _builder.append("\t                      ");
    _builder.append("</button>");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("</form>");
    _builder.newLine();
    _builder.append("\t              ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("</li>");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("<!-- Nav Item - Alerts -->");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("{% comment %} <li class=\"nav-item dropdown no-arrow mx-1\">");
    _builder.newLine();
    _builder.append("\t              ");
    _builder.append("<a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"alertsDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("<i class=\"fas fa-bell fa-fw\"></i>");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("<!-- Counter - Alerts -->");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("<span class=\"badge badge-danger badge-counter\">3+</span>");
    _builder.newLine();
    _builder.append("\t              ");
    _builder.append("</a>");
    _builder.newLine();
    _builder.append("\t              ");
    _builder.append("<!-- Dropdown - Alerts -->");
    _builder.newLine();
    _builder.append("\t              ");
    _builder.append("<div class=\"dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in\" aria-labelledby=\"alertsDropdown\">");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("<h6 class=\"dropdown-header\">");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("Alerts Center");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("</h6>");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("<a class=\"dropdown-item d-flex align-items-center\" href=\"#\">");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("<div class=\"mr-3\">");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("<div class=\"icon-circle bg-primary\">");
    _builder.newLine();
    _builder.append("\t                      ");
    _builder.append("<i class=\"fas fa-file-alt text-white\"></i>");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("<div>");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("<div class=\"small text-gray-500\">December 12, 2019</div>");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("<span class=\"font-weight-bold\">A new monthly report is ready to download!</span>");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("</a>");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("<a class=\"dropdown-item d-flex align-items-center\" href=\"#\">");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("<div class=\"mr-3\">");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("<div class=\"icon-circle bg-success\">");
    _builder.newLine();
    _builder.append("\t                      ");
    _builder.append("<i class=\"fas fa-donate text-white\"></i>");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("<div>");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("<div class=\"small text-gray-500\">December 7, 2019</div>");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("$290.29 has been deposited into your account!");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("</a>");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("<a class=\"dropdown-item d-flex align-items-center\" href=\"#\">");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("<div class=\"mr-3\">");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("<div class=\"icon-circle bg-warning\">");
    _builder.newLine();
    _builder.append("\t                      ");
    _builder.append("<i class=\"fas fa-exclamation-triangle text-white\"></i>");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("<div>");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("<div class=\"small text-gray-500\">December 2, 2019</div>");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("Spending Alert: We\'ve noticed unusually high spending for your account.");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("</a>");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("<a class=\"dropdown-item text-center small text-gray-500\" href=\"#\">Show All Alerts</a>");
    _builder.newLine();
    _builder.append("\t              ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("</li>");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("<!-- Nav Item - Messages -->");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("<li class=\"nav-item dropdown no-arrow mx-1\">");
    _builder.newLine();
    _builder.append("\t              ");
    _builder.append("<a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"messagesDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("<i class=\"fas fa-envelope fa-fw\"></i>");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("<!-- Counter - Messages -->");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("<span class=\"badge badge-danger badge-counter\">7</span>");
    _builder.newLine();
    _builder.append("\t              ");
    _builder.append("</a>");
    _builder.newLine();
    _builder.append("\t              ");
    _builder.append("<!-- Dropdown - Messages -->");
    _builder.newLine();
    _builder.append("\t              ");
    _builder.append("<div class=\"dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in\" aria-labelledby=\"messagesDropdown\">");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("<h6 class=\"dropdown-header\">");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("Message Center");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("</h6>");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("<a class=\"dropdown-item d-flex align-items-center\" href=\"#\">");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("<div class=\"dropdown-list-image mr-3\">");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("<img class=\"rounded-circle\" src=\"https://source.unsplash.com/fn_BT9fwg_E/60x60\" alt=\"\">");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("<div class=\"status-indicator bg-success\"></div>");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("<div class=\"font-weight-bold\">");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("<div class=\"text-truncate\">Hi there! I am wondering if you can help me with a problem I\'ve been having.</div>");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("<div class=\"small text-gray-500\">Emily Fowler · 58m</div>");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("</a>");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("<a class=\"dropdown-item d-flex align-items-center\" href=\"#\">");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("<div class=\"dropdown-list-image mr-3\">");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("<img class=\"rounded-circle\" src=\"https://source.unsplash.com/AU4VPcFN4LE/60x60\" alt=\"\">");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("<div class=\"status-indicator\"></div>");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("<div>");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("<div class=\"text-truncate\">I have the photos that you ordered last month, how would you like them sent to you?</div>");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("<div class=\"small text-gray-500\">Jae Chun · 1d</div>");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("</a>");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("<a class=\"dropdown-item d-flex align-items-center\" href=\"#\">");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("<div class=\"dropdown-list-image mr-3\">");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("<img class=\"rounded-circle\" src=\"https://source.unsplash.com/CS2uCrpNzJY/60x60\" alt=\"\">");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("<div class=\"status-indicator bg-warning\"></div>");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("<div>");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("<div class=\"text-truncate\">Last month\'s report looks great, I am very happy with the progress so far, keep up the good work!</div>");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("<div class=\"small text-gray-500\">Morgan Alvarez · 2d</div>");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("</a>");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("<a class=\"dropdown-item d-flex align-items-center\" href=\"#\">");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("<div class=\"dropdown-list-image mr-3\">");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("<img class=\"rounded-circle\" src=\"https://source.unsplash.com/Mv9hjnEUHR4/60x60\" alt=\"\">");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("<div class=\"status-indicator bg-success\"></div>");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("<div>");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("<div class=\"text-truncate\">Am I a good boy? The reason I ask is because someone told me that people say this to all dogs, even if they aren\'t good...</div>");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("<div class=\"small text-gray-500\">Chicken the Dog · 2w</div>");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("</a>");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("<a class=\"dropdown-item text-center small text-gray-500\" href=\"#\">Read More Messages</a>");
    _builder.newLine();
    _builder.append("\t              ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("</li> {% endcomment %}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("<div class=\"topbar-divider d-none d-sm-block\"></div>");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("<!-- Nav Item - User Information -->");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("<li class=\"nav-item dropdown no-arrow\">");
    _builder.newLine();
    _builder.append("\t              ");
    _builder.append("<a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"userDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("<span class=\"mr-2 d-none d-lg-inline text-gray-600 small\">");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("{% if user.is_authenticated %}");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("{{ user.first_name }}");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("{{ user.last_name }}");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("{% else %}");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("Usuário não logado");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("{% endif %}</span>");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("<img class=\"img-profile rounded-circle\" src=\"https://upload.wikimedia.org/wikipedia/commons/7/72/Default-welcomer.png\">");
    _builder.newLine();
    _builder.append("\t              ");
    _builder.append("</a>");
    _builder.newLine();
    _builder.append("\t              ");
    _builder.append("<!-- Dropdown - User Information -->");
    _builder.newLine();
    _builder.append("\t              ");
    _builder.append("<div class=\"dropdown-menu dropdown-menu-right shadow animated--grow-in\" aria-labelledby=\"userDropdown\">");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("<a class=\"dropdown-item\" href=\"#\">");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("<i class=\"fas fa-user fa-sm fa-fw mr-2 text-gray-400\"></i>");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("Profile");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("</a>");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("<a class=\"dropdown-item\" href=\"#\">");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("<i class=\"fas fa-cogs fa-sm fa-fw mr-2 text-gray-400\"></i>");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("Settings");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("</a>");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("<a class=\"dropdown-item\" href=\"#\">");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("<i class=\"fas fa-list fa-sm fa-fw mr-2 text-gray-400\"></i>");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("Activity Log");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("</a>");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("<div class=\"dropdown-divider\"></div>");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("<a class=\"dropdown-item\" data-toggle=\"modal\" data-target=\"#logoutModal\">");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("<i class=\"fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400\"></i>");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("Logout");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("</a>");
    _builder.newLine();
    _builder.append("\t              ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("</li>");
    _builder.newLine();
    _builder.append("\t          ");
    _builder.append("</ul>");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("</nav>");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("<!-- End of Topbar -->");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("<!-- Begin Page Content -->");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("<div class=\"container-fluid\" id=\"dgen-content\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t          ");
    _builder.append("{% if messages %}");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("{% for message in messages %}");
    _builder.newLine();
    _builder.append("\t              ");
    _builder.append("<div class=\"text-center alert alert-{{ message.tags }} alert-dismissible fade show\" role=\"alert\" style=\"margin: auto; width: 80%;\">");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("{{ message|safe }}");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("<button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\">");
    _builder.newLine();
    _builder.append("\t                  ");
    _builder.append("<span aria-hidden=\"true\">&times;</span>");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("</button>");
    _builder.newLine();
    _builder.append("\t              ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("{% endfor %}");
    _builder.newLine();
    _builder.append("\t          ");
    _builder.append("{% endif %}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t          ");
    _builder.append("{% block content %}");
    _builder.newLine();
    _builder.append("\t          ");
    _builder.append("{% endblock %}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("<!-- /.container-fluid -->");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t      ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t      ");
    _builder.append("<!-- End of Main Content -->");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t      ");
    _builder.append("<!-- Footer -->");
    _builder.newLine();
    _builder.append("\t      ");
    _builder.append("<footer class=\"sticky-footer bg-white\">");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("<div class=\"container my-auto\">");
    _builder.newLine();
    _builder.append("\t          ");
    _builder.append("<div class=\"copyright text-center my-auto\">");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("<span>Copyright &copy; Dgen 2021</span>");
    _builder.newLine();
    _builder.append("\t          ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t      ");
    _builder.append("</footer>");
    _builder.newLine();
    _builder.append("\t      ");
    _builder.append("<!-- End of Footer -->");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("<!-- End of Content Wrapper -->");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("<!-- End of Page Wrapper -->");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("<!-- Scroll to Top Button-->");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("<a class=\"scroll-to-top rounded\" href=\"#page-top\">");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("<i class=\"fas fa-angle-up\"></i>");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("</a>");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("<!-- Logout Modal-->");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("<div class=\"modal fade\" id=\"logoutModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("<div class=\"modal-dialog\" role=\"document\">");
    _builder.newLine();
    _builder.append("\t      ");
    _builder.append("<div class=\"modal-content\">");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("<div class=\"modal-header\">");
    _builder.newLine();
    _builder.append("\t          ");
    _builder.append("<h5 class=\"modal-title\" id=\"exampleModalLabel\">Pronto para sair?</h5>");
    _builder.newLine();
    _builder.append("\t          ");
    _builder.append("<button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("<span aria-hidden=\"true\">×</span>");
    _builder.newLine();
    _builder.append("\t          ");
    _builder.append("</button>");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("<div class=\"modal-body\">Escolha \"Logout\" abaixo se você está pronto para finalizar a sessão atual.</div>");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("<div class=\"modal-footer\">");
    _builder.newLine();
    _builder.append("\t          ");
    _builder.append("<button class=\"btn btn-secondary\" type=\"button\" data-dismiss=\"modal\">Cancelar</button>");
    _builder.newLine();
    _builder.append("\t          ");
    _builder.append("<a class=\"btn btn-primary\">Logout</a>");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t      ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("<!-- Bootstrap core JavaScript-->");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css\" integrity=\"sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO\" crossorigin=\"anonymous\">");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("<script src=\"{% static \'vendor/jquery/jquery.min.js\' %}\"></script>");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("<script src=\"{% static \'vendor/bootstrap/js/bootstrap.bundle.min.js\' %}\"></script>");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("<!-- Core plugin JavaScript-->");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("<script src=\"{% static \'vendor/jquery-easing/jquery.easing.min.js\' %}\"></script>");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("<!-- Custom scripts for all pages-->");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("<script src=\"{% static \'js/sb-admin-2.min.js\' %}\"></script>");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("<!-- Page level plugins -->");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("{% comment %} <script src=\"{% static \'vendor/chart.js/Chart.min.js\' %}\"></script> {% endcomment %}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("<!-- Page level custom scripts -->");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("{% comment %} <script src=\"{% static \'js/demo/chart-area-demo.js\' %}\"></script>");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("<script src=\"{% static \'js/demo/chart-pie-demo.js\' %}\"></script> {% endcomment %}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</body>");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</html>");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    return _builder;
  }
}
