/*
 * generated by Xtext 2.25.0
 */
package org.xtext.mdd.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.mdd.parser.antlr.internal.InternalDgenParser;
import org.xtext.mdd.services.DgenGrammarAccess;

public class DgenParser extends AbstractAntlrParser {

	@Inject
	private DgenGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDgenParser createParser(XtextTokenStream stream) {
		return new InternalDgenParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Domainmodel";
	}

	public DgenGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DgenGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
