/*
 * generated by Xtext 2.25.0
 */
package org.xtext.mdd.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.mdd.dgen.ui.internal.DgenActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DgenExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(DgenActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		DgenActivator activator = DgenActivator.getInstance();
		return activator != null ? activator.getInjector(DgenActivator.ORG_XTEXT_MDD_DGEN) : null;
	}

}
