/*
 * generated by Xtext 2.25.0
 */
package org.xtext.mdd.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.mdd.dgen.DataType;
import org.xtext.mdd.dgen.DgenPackage;
import org.xtext.mdd.dgen.Domainmodel;
import org.xtext.mdd.dgen.Entity;
import org.xtext.mdd.dgen.Feature;
import org.xtext.mdd.dgen.ViewGroup;
import org.xtext.mdd.dgen.ViewOptions;
import org.xtext.mdd.dgen.Views;
import org.xtext.mdd.services.DgenGrammarAccess;

@SuppressWarnings("all")
public class DgenSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private DgenGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == DgenPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case DgenPackage.DATA_TYPE:
				sequence_DataType(context, (DataType) semanticObject); 
				return; 
			case DgenPackage.DOMAINMODEL:
				sequence_Domainmodel(context, (Domainmodel) semanticObject); 
				return; 
			case DgenPackage.ENTITY:
				sequence_Entity(context, (Entity) semanticObject); 
				return; 
			case DgenPackage.FEATURE:
				sequence_Feature(context, (Feature) semanticObject); 
				return; 
			case DgenPackage.VIEW_GROUP:
				sequence_ViewGroup(context, (ViewGroup) semanticObject); 
				return; 
			case DgenPackage.VIEW_OPTIONS:
				sequence_ViewOptions(context, (ViewOptions) semanticObject); 
				return; 
			case DgenPackage.VIEWS:
				sequence_Views(context, (Views) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Type returns DataType
	 *     DataType returns DataType
	 *
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_DataType(ISerializationContext context, DataType semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DgenPackage.Literals.TYPE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DgenPackage.Literals.TYPE__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDataTypeAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Domainmodel returns Domainmodel
	 *
	 * Constraint:
	 *     elements+=Type+
	 */
	protected void sequence_Domainmodel(ISerializationContext context, Domainmodel semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Type returns Entity
	 *     Entity returns Entity
	 *
	 * Constraint:
	 *     (views=Views name=ID superType=[Entity|ID]? features+=Feature+)
	 */
	protected void sequence_Entity(ISerializationContext context, Entity semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Feature returns Feature
	 *
	 * Constraint:
	 *     (many?='many'? name=ID optional?='?'? type=[Type|ID])
	 */
	protected void sequence_Feature(ISerializationContext context, Feature semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ViewGroup returns ViewGroup
	 *
	 * Constraint:
	 *     (name='All' | name='None')
	 */
	protected void sequence_ViewGroup(ISerializationContext context, ViewGroup semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ViewOptions returns ViewOptions
	 *
	 * Constraint:
	 *     (name='Create' | name='Read' | name='Update' | name='Delete')
	 */
	protected void sequence_ViewOptions(ISerializationContext context, ViewOptions semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Views returns Views
	 *
	 * Constraint:
	 *     (viewGroup=ViewGroup | viewOption+=ViewOptions+)
	 */
	protected void sequence_Views(ISerializationContext context, Views semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
